% Function create_toolbar(fig)   
% 
% This function is to create the toolbar for the interface, and it is 
% originally from function filtview() in DSP toolbox but modified to
% be used in VTAR program.
% 
%   Last time updated   -   06/01/2004, xinhui zhou
% ---------------------------------------------------------------------


function create_toolbar(fig) ;   % create toolbar to zoom , measure the value and print ...  
% CREATE_TOOLBAR Creates the toolbar for the Filter Viewer.
%
global VT ;
load siggui_vtar  %_icons for toolbar buttons
ut = uitoolbar(fig);

ud.toolbar.open = ...
    uipushtool('cdata', bmp.open ,...
                 'parent',ut,...
                 'clickedcallback', 'vtar(''Load_Callback'',gcbo,[],guidata(gcbo))',...
                 'tooltipstring',xlate('Load previous area function setting and calculation result')); 

ud.toolbar.save = ...
    uipushtool('cdata', bmp.save ,...
                 'parent',ut,...
                 'clickedcallback', 'vtar(''Save_Callback'',gcbo,[],guidata(gcbo))',...
                 'tooltipstring',xlate('Save current area function setting and calculation result')); 

ud.toolbar.print = ...
    uipushtool('cdata',bmp.print,...
                 'parent',ut,...
                 'clickedcallback','printcomp(''prnt'')' ,...
                 'tooltipstring',xlate('Print...'));
ud.toolbar.printpreview = ...
    uipushtool('cdata',bmp.printpreview,...
                 'parent',ut,...
                 'clickedcallback','printcomp(''prev'')' ,...
                 'tooltipstring',xlate('Print Preview...'));
ud.toolbar.mousezoom = ...
    uitoggletool('cdata',bmp.mousezoom,...
                 'separator','on',...
                 'parent',ut,...
                 'clickedcallback','sbswitch(''fvzoom'',''mousezoom'')',...
                 'tooltipstring',xlate('Mouse Zoom'));
ud.toolbar.fullviewall = ...
    uipushtool('cdata',bmp.fullviewall,...
                 'parent',ut,...
                 'clickedcallback','sbswitch(''fvzoom'',''zoomout'',''all'')',...
                 'tooltipstring',xlate('Full View All (zooms out both axes, all plots)')); 
ud.toolbar.fullview = ...
    uipushtool('cdata',bmp.fullview,...
                 'parent',ut,...
                 'clickedcallback','sbswitch(''fvzoom'',''zoomout'')',...
                 'tooltipstring',xlate('Full View (zooms out both axes, selected plot)')); 

             % 04/08/2004, xinhui added
ud.toolbar.adaptview = ...
    uipushtool('cdata',bmp.areaplot,...
                 'parent',ut,...
                 'clickedcallback', 'plotcontextmenu(gcbo, 2)',...
                 'tooltipstring',xlate('Display all plots and make plots for area function have same xlim, and ylim')); 
             
ud.toolbar.zoominy = ...
    uipushtool('cdata',bmp.zoominy,...
                 'parent',ut,...
                 'clickedcallback','sbswitch(''fvzoom'',''zoominy'')',...
                 'tooltipstring',xlate('Zoom In - Y (vertical axis)'));
ud.toolbar.zoomouty = ...
    uipushtool('cdata',bmp.zoomouty,...
                 'parent',ut,...
                 'clickedcallback','sbswitch(''fvzoom'',''zoomouty'')',...
                 'tooltipstring',xlate('Zoom Out - Y (vertical axis)'));
ud.toolbar.zoominx = ...
    uipushtool('cdata',bmp.zoominx,...
                 'parent',ut,...
                 'clickedcallback','sbswitch(''fvzoom'',''zoominx'')',...
                 'tooltipstring',xlate('Zoom In - X (horizontal axis)'));
ud.toolbar.zoomoutx = ...
    uipushtool('cdata',bmp.zoomoutx,...
                 'parent',ut,...
                 'clickedcallback','sbswitch(''fvzoom'',''zoomoutx'')',...
                 'tooltipstring',xlate('Zoom Out - X (horizontal axis)'));

             % 07/09/2004, xinhui added
ud.toolbar.hold = ...
    uipushtool('cdata',bmp.hold,...
                 'parent',ut,...
                  'separator','on',...
                 'clickedcallback', 'holdPlots(''holdOn'')',...
                 'tooltipstring',xlate('Hold on the plots for the current area function setting, in order to do comparision betw. different settings')); 

ud.toolbar.holdClear = ...
    uipushtool('cdata',bmp.holdClear,...
                 'parent',ut,...
                  'separator','off',...
                 'clickedcallback', 'holdPlots(''holdOff'')',...
                 'tooltipstring',xlate('Clear all the plots which have been held on')); 
             
% ud.toolbar.select = ...
%     uipushtool('cdata',bmp.select,...
%                  'parent',ut,...
%                  'clickedcallback','sbswitch(''sptlegend'',''popup'')' ,...
%                  'tooltipstring',xlate('Select signal...'));
% ud.toolbar.lineprop = ...
%     uipushtool('cdata',bmp.lineprop,...
%                  'parent',ut,...
%                  'clickedcallback','sbswitch(''sptlegend'',''button'')' ,...
%                  'tooltipstring',xlate('Line Properties...'));

ud.toolbar = ruler('toolbarbuttons',ud.toolbar,ut,bmp);

% ud.toolbar.whatsthis = ...
%     uitoggletool('cdata',bmp.whatsthis,...
%                  'parent',ut,...
%                  'separator','on',...
%                  'clickedcallback','sbswitch(''filtview'',''help'')' ,...
%                  'tooltipstring',xlate('"What''s This?" Help'));


% xinhui commented this 04-17-2004
% ud.toolbar.whatsthis = ...
%     uitoggletool('cdata',bmp.whatsthis,...
%                  'parent',ut,...
%                  'separator','on',...
%                  'clickedcallback',' ' ,...
%                  'tooltipstring',xlate('"What''s This?" Help'));

% ud.toolbar.whatsthis = ...
%     uitoggletool('cdata',[ ],...
%                  'parent',ut,...
%                  'separator','on',...
%                  'clickedcallback',' ' ,...
%                  'tooltipstring',xlate('Toolbar'));

            % 10/20/2006 , xinhui added
ud.toolbar.synthesis = ...
    uipushtool('cdata',[bmp.synthesis ],...
                 'parent',ut,...
                 'separator','on',...
                 'clickedcallback','playsound' ,...
                 'tooltipstring',xlate('Sound synthesis'));
ud.toolbar.sensitivity = ...
    uipushtool('cdata',[ bmp.sensitivity],...
                 'parent',ut,...
                 'separator','off',...
                 'clickedcallback','Sensitivity_function' ,...
                 'tooltipstring',xlate('Formant sensitivity function'));
 %bmp.sensitivity = double(temp2)/255 ;

ud.toolbar.susceptance = ...
    uipushtool('cdata',[bmp.susceptance ],...
                 'parent',ut,...
                 'separator','off',...
                 'clickedcallback','susceptance_gui' ,...
                 'tooltipstring',xlate('Susceptance plot'));

             % 05/26/2004, xinhui added
ud.toolbar.run = ...
    uipushtool('cdata',bmp.run,...
                 'parent',ut,...
                  'separator','on',...
                 'clickedcallback', 'vtar(''Apply_Callback'',gcbo,[],guidata(gcbo))',...
                 'tooltipstring',xlate('Calculate the acoustic response based on the area function setting')); 
             
VT.toolbar = ud.toolbar ;

%------------ end of function -------------------------
